#基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

# ブランチやタグを指定したいとき
[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

# 特定の条件で読み込みたいとき
[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

# 依存関係を指定したいとき
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

# 依存関係を指定したからと言って、自動でインストールはされない（ここは NeoBundle と違う）
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#[[plugins]]
#repo = 'tchyny/lightline.vim'
#hook_add = '''
#    let g:lightline = {'colorscheme': 'wombat'}
#'''

[[plugins]]
repo = 'sbdchd/neoformat'

[[plugins]]
repo = 'tomasr/molokai'

#[[plugins]]
#repo = 'thinca/vim-ref'

[[plugins]]
repo = 'mojako/ref-sources.vim'

[[plugins]]
repo  = 'scrooloose/nerdtree'

#[[plugins]]
#repo  = 'scrooloose/syntastic'

[[plugins]]
repo  = 'editorconfig/editorconfig-vim'

[[plugins]]
repo  = 'Townk/vim-autoclose'

[[plugins]]
repo  = 'tpope/vim-fugitive'

[[plugins]]
repo  = 'gregsexton/gitv'

#[[plugins]]
#repo  = 'soramugi/auto-ctags.vim'

